[package]
name = "kcpgateway"
version = "0.1.0"
authors = ["yi lu <luyikk@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
net2 = "0.2"
num_cpus="1.8"
log="0.4.11"
bytes = "0.5.6"
chrono="0.4"
mimalloc = "0.1.20"
ahash = "0.4.5"
xbinary = "0.1.2"
async-trait = "0.1.40"
async-mutex = "1.4.0"
lazy_static = "1.4.0"
json = "0.12.4"
flexi_logger = "0.16.1"

[profile.release]
lto = "fat"
codegen-units = 1
